on: push

jobs:
  test_and_compile:
    runs-on: ubuntu-latest
    name: test and compile
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y pandoc lmodern wkhtmltopdf
      - run: make test
      - run: make
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output/
